name: benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: 
  path: ^1.7.0
  random_string: ^2.0.1
  get_storage:
    path: ..
  hive: 
  sqflite: 
  shared_preferences: 
  fl_chart: 0.1.6
  moor_ffi: 

flutter:
  uses-material-design: true